### ISSUE TITLE
TypeError: Cannot write to hid device on rival 3 wireless

### ISSUE THREAD

**Issue by sowa705** [mtadin/steelseries-wireless-battery-tray#24]
Hi, i have no idea if this mouse is compatible but it seems to try doing something with this error:

```
ERROR while writing data: TypeError: Cannot write to hid device
    at E:\downloads\steelseries-wireless-battery-tray-win32-x64-2.0.0-beta\resources\app\main.js:35:20
    at Array.forEach (<anonymous>)
    at readDeviceData (E:\downloads\steelseries-wireless-battery-tray-win32-x64-2.0.0-beta\resources\app\main.js:27:13)
    at mainFunction (E:\downloads\steelseries-wireless-battery-tray-win32-x64-2.0.0-beta\resources\app\main.js:99:3)
    at App.<anonymous> (E:\downloads\steelseries-wireless-battery-tray-win32-x64-2.0.0-beta\resources\app\main.js:107:3)    at App.emit (node:events:513:28)
(node:14076) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'toString')
    at Jimp.print (E:\downloads\steelseries-wireless-battery-tray-win32-x64-2.0.0-beta\resources\app\node_modules\@jimp\plugin-print\dist\index.js:224:23)
    at E:\downloads\steelseries-wireless-battery-tray-win32-x64-2.0.0-beta\resources\app\main.js:92:13
(Use `steelseries-wireless-battery-tray --trace-warnings ...` to show where the warning was created)
(node:14076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by mtadin** [comment]
Unfortunately, mice and keyboards are not supported as stated in the [readme](https://github.com/mtadin/steelseries-wireless-battery-tray#limitations)
